# Generated by Django 3.0.3 on 2021-07-20 08:14

from django.db import migrations, models
import django.db.models.deletion
import eshop_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری محصول', 'verbose_name_plural': 'گالری محصولات'},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.Product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=eshop_product.models.upload_gallery_image_path, verbose_name='تصویر'),
        ),
    ]
