# Generated by Django 3.0.3 on 2021-06-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
